### ISSUE TITLE
Block sizes are smaller, than it's text content. An example code below. I've tested it on viz-js.com

### ISSUE THREAD

**Issue by igoryonya** [mdaines/viz.js#97] opened 2017-11-02 20:40 UTC
digraph G {
    fontname = "Bitstream Vera Sans"
        fontsize = 8
        node [
            fontname = "Bitstream Vera Sans"
            fontsize = 8
            shape = "record"
        ]
        edge [
            fontname = "Bitstream Vera Sans"
            fontsize = 8
        ]
        Animal [
            label = "{Animal|+ name : string\l+ age : int\l|+ die() : void\l}"
        ]
}

**Comment by magjac** [comment] 2017-11-03 07:39
Due to https://github.com/mdaines/viz.js/issues/82?

**Comment by magjac** [comment] 2017-11-03 07:40
Duplicate of https://github.com/mdaines/viz.js/issues/81?

**Closed** 2018-01-30 20:26 UTC
Labels: duplicate
