### ISSUE TITLE
Text not rendering in nodes

### ISSUE THREAD

**Issue by phlpl** [mdaines/viz.js#218] opened 2023-10-23 16:28 UTC
I have an issue rendering the following graph.  It will render on the [website](https://viz-js.com/), but will not render using the library.  

Screenshot of graph below.

``` dot
digraph test_labels {
  bgcolor=transparent;
  rankdir=TB;
  splines=polyline;
  
  node [shape = point]; _start_
  node [shape = oval];
  edge [dir=forward];
  
  _start_ -> "Node A";
  "Node A" -> x1;
  x1 [shape=plaintext, label="Transition X"]; 
  x1 -> "Node B";
  "Node B" -> x2;
  x2 [shape=plaintext, label="Transition Y"]; 
  x2 -> "Node C";
  "Node B" -> x3;
  x3 [shape=plaintext, label="Transition Z"]; 
  x3 -> "Node D"; 
}
```

![2023-10-23_17-07 render issue](https://github.com/mdaines/viz-js/assets/9218510/b52626ab-5119-4de5-bbdf-524ab04b9a5f)

**Comment by mdaines** [comment] 2023-10-23 17:11
It looks like the issue is specifically that the node labels ("Node A", etc.) aren't showing up, is that correct?

I was able to reproduce this, but I haven't figured out yet why it's happening.

**Comment by phlpl** [comment] 2023-10-23 17:22
Yes that is correct, the node labels aren't rendering, but are rendering fine in the editor.

**Comment by mdaines** [comment] 2023-10-23 17:23
This graph seems to have the same issue:

```dot
digraph {
  a -> b;
  b [label="test"];
}
```

When I render this graph with the `dot` program or the viz-js.com website, the node `a` has the label "a" as expected. When I render it by pasting the source into the script-tag example, the node `a` has no label.

As a workaround, I can explicitly set the label for the node `a`:

```dot
digraph {
  a -> b;
  a [label="a"];
  b [label="test"];
}
```

But I think it should work without having to do that.

**Comment by phlpl** [comment] 2023-10-23 17:31
Thanks for the workaround, works as expected if I make them all IDs.

**Comment by mdaines** [comment] 2023-10-23 17:46
I hope the workaround will be OK for now. But this shouldn't happen. I can take another look at it later.

A few more notes:

The issue appears in the parcel example as well, and apparently only on the first call to `renderSVGElement`, etc.

If I render to "dot" format instead, I can see that the result of the first call omits the `node [label="\N"]` statement that Graphviz usually inserts.

If I call the `graphvizVersion` getter before rendering, the issue doesn't appear:

```js
Viz.instance().then(function(viz) {
  console.log(viz.graphvizVersion);
  document.body.appendChild(viz.renderSVGElement("digraph { a -> b; b [label=test]; }"));
});
```

**Comment by mdaines** [comment] 2023-10-24 02:14
I was able to reproduce this using Graphviz as a library from C, so it looks like this isn't a Viz.js issue. I'm going to close this and open an issue on the Graphviz bug tracker instead.

Since it only occurs on the first render, I think the reason it looks like it doesn't occur on the website is that usually the first render is the sample graph `digraph { a -> b }`. If the [reduced example above](https://viz-js.com/?dot=ZGlncmFwaCB7CiAgYSAtPiBiOwogIGIgW2xhYmVsPSJ0ZXN0Il07Cn0K) is rendered first (as when clicking on that link) the issue does occur.

**Comment by mdaines** [comment] 2023-10-24 02:18
Actually, I'm going to reopen this in case the problem is my incorrect usage of the Graphviz API.

**Comment by phlpl** [comment] 2023-10-24 07:27
Strange behaviour.  That explains why it works on the website but not through the library.

**Comment by mdaines** [comment] 2023-10-25 20:29
I think this may be the same issue: https://gitlab.com/graphviz/graphviz/-/issues/2434

**Closed as completed** 2023-10-25 21:23 UTC

**Comment by mdaines** [comment] 2023-10-26 16:14
I've released the workaround in 3.2.3.

**Comment by phlpl** [comment] 2023-10-27 07:46
I tested this with the update but still got the same result.

**Comment by phlpl** [comment] 2023-10-27 07:56
I updated the script-tag package version and tested this and it works as expected.  Nice one!
